-- Drug Catalog Seed
-- Inserts built-in Indian allopathic brands + homeopathic medicines.
-- Run via: npm run migrate  OR  psql $DATABASE_URL -f migrations/038_drug_catalog_seed.sql
--
-- For the full 50k–200k dataset run AFTER this migration:
--   bash scripts/seed_drugs.sh /path/to/indian_drugs.csv

INSERT INTO drug_catalog (brand_name, generic_name, manufacturer, strength, dosage_form, category) VALUES

-- ── Allopathy: Common Indian Brands ──────────────────────────────────────────
('Dolo 650',           'Paracetamol',                             NULL, '650mg',    'Tablet',    'allopathy'),
('Calpol',             'Paracetamol',                             NULL, '500mg',    'Tablet',    'allopathy'),
('Crocin',             'Paracetamol',                             NULL, '500mg',    'Tablet',    'allopathy'),
('Pan-D',              'Pantoprazole + Domperidone',              NULL, '40mg+10mg','Capsule',   'allopathy'),
('Pan 40',             'Pantoprazole',                            NULL, '40mg',     'Tablet',    'allopathy'),
('Pantop',             'Pantoprazole',                            NULL, '40mg',     'Tablet',    'allopathy'),
('Omez',               'Omeprazole',                              NULL, '20mg',     'Capsule',   'allopathy'),
('Rantac',             'Ranitidine',                              NULL, '150mg',    'Tablet',    'allopathy'),
('Gelusil',            'Aluminium Hydroxide + Magnesium Hydroxide',NULL,NULL,       'Suspension','allopathy'),
('Digene',             'Antacid',                                 NULL, NULL,       'Tablet',    'allopathy'),
('Azithral',           'Azithromycin',                            NULL, '500mg',    'Tablet',    'allopathy'),
('Zithromax',          'Azithromycin',                            NULL, '250mg',    'Tablet',    'allopathy'),
('Moxikind-CV',        'Amoxicillin + Clavulanic Acid',           NULL, '625mg',    'Tablet',    'allopathy'),
('Augmentin',          'Amoxicillin + Clavulanic Acid',           NULL, '625mg',    'Tablet',    'allopathy'),
('Clavam',             'Amoxicillin + Clavulanic Acid',           NULL, '625mg',    'Tablet',    'allopathy'),
('Amoxil',             'Amoxicillin',                             NULL, '500mg',    'Capsule',   'allopathy'),
('Amoxyclav',          'Amoxicillin + Clavulanic Acid',           NULL, '625mg',    'Tablet',    'allopathy'),
('Cifran',             'Ciprofloxacin',                           NULL, '500mg',    'Tablet',    'allopathy'),
('Ciplox',             'Ciprofloxacin',                           NULL, '500mg',    'Tablet',    'allopathy'),
('Norflox',            'Norfloxacin',                             NULL, '400mg',    'Tablet',    'allopathy'),
('Levoflox',           'Levofloxacin',                            NULL, '500mg',    'Tablet',    'allopathy'),
('Levoquin',           'Levofloxacin',                            NULL, '500mg',    'Tablet',    'allopathy'),
('Monocef',            'Ceftriaxone',                             NULL, '1g',       'Injection', 'allopathy'),
('Taxim-O',            'Cefixime',                                NULL, '200mg',    'Tablet',    'allopathy'),
('Cepodem',            'Cefpodoxime',                             NULL, '200mg',    'Tablet',    'allopathy'),
('Supacef',            'Cefuroxime',                              NULL, '250mg',    'Tablet',    'allopathy'),
('Metrogyl',           'Metronidazole',                           NULL, '400mg',    'Tablet',    'allopathy'),
('Flagyl',             'Metronidazole',                           NULL, '400mg',    'Tablet',    'allopathy'),
('Tiniba',             'Tinidazole',                              NULL, '500mg',    'Tablet',    'allopathy'),
('Dexona',             'Dexamethasone',                           NULL, '0.5mg',    'Tablet',    'allopathy'),
('Wysolone',           'Prednisolone',                            NULL, '5mg',      'Tablet',    'allopathy'),
('Medrol',             'Methylprednisolone',                      NULL, '4mg',      'Tablet',    'allopathy'),
('Becosules',          'Vitamin B Complex',                       NULL, NULL,       'Capsule',   'allopathy'),
('Neurobion',          'Vitamin B Complex',                       NULL, NULL,       'Tablet',    'allopathy'),
('Shelcal',            'Calcium + Vitamin D3',                    NULL, '500mg',    'Tablet',    'allopathy'),
('Calcirol',           'Cholecalciferol (Vitamin D3)',            NULL, '60000 IU', 'Sachet',    'allopathy'),
('Uprise-D3',          'Cholecalciferol',                         NULL, '60000 IU', 'Capsule',   'allopathy'),
('Limcee',             'Vitamin C',                               NULL, '500mg',    'Tablet',    'allopathy'),
('Zincovit',           'Zinc + Multivitamin',                     NULL, NULL,       'Tablet',    'allopathy'),
('Atorfit',            'Atorvastatin',                            NULL, '10mg',     'Tablet',    'allopathy'),
('Storvas',            'Atorvastatin',                            NULL, '10mg',     'Tablet',    'allopathy'),
('Lipitor',            'Atorvastatin',                            NULL, '20mg',     'Tablet',    'allopathy'),
('Rozavel',            'Rosuvastatin',                            NULL, '10mg',     'Tablet',    'allopathy'),
('Crestor',            'Rosuvastatin',                            NULL, '10mg',     'Tablet',    'allopathy'),
('Ecosprin',           'Aspirin',                                 NULL, '75mg',     'Tablet',    'allopathy'),
('Disprin',            'Aspirin',                                 NULL, '325mg',    'Tablet',    'allopathy'),
('Clexane',            'Enoxaparin',                              NULL, '40mg',     'Injection', 'allopathy'),
('Losar',              'Losartan',                                NULL, '50mg',     'Tablet',    'allopathy'),
('Telma',              'Telmisartan',                             NULL, '40mg',     'Tablet',    'allopathy'),
('Telvas',             'Telmisartan',                             NULL, '40mg',     'Tablet',    'allopathy'),
('Amlodac',            'Amlodipine',                              NULL, '5mg',      'Tablet',    'allopathy'),
('Amlovas',            'Amlodipine',                              NULL, '5mg',      'Tablet',    'allopathy'),
('Stamlo',             'Amlodipine',                              NULL, '5mg',      'Tablet',    'allopathy'),
('Metolar',            'Metoprolol',                              NULL, '50mg',     'Tablet',    'allopathy'),
('Atenolol',           'Atenolol',                                NULL, '50mg',     'Tablet',    'allopathy'),
('Tenormin',           'Atenolol',                                NULL, '50mg',     'Tablet',    'allopathy'),
('Januvia',            'Sitagliptin',                             NULL, '100mg',    'Tablet',    'allopathy'),
('Galvus',             'Vildagliptin',                            NULL, '50mg',     'Tablet',    'allopathy'),
('Trajenta',           'Linagliptin',                             NULL, '5mg',      'Tablet',    'allopathy'),
('Glucophage',         'Metformin',                               NULL, '500mg',    'Tablet',    'allopathy'),
('Glycomet',           'Metformin',                               NULL, '500mg',    'Tablet',    'allopathy'),
('Glimy',              'Glimepiride',                             NULL, '1mg',      'Tablet',    'allopathy'),
('Amaryl',             'Glimepiride',                             NULL, '2mg',      'Tablet',    'allopathy'),
('Cetrizine',          'Cetirizine',                              NULL, '10mg',     'Tablet',    'allopathy'),
('Cetirizine',         'Cetirizine',                              NULL, '10mg',     'Tablet',    'allopathy'),
('Levocet',            'Levocetirizine',                          NULL, '5mg',      'Tablet',    'allopathy'),
('Montek LC',          'Montelukast + Levocetirizine',            NULL, '10mg+5mg', 'Tablet',    'allopathy'),
('Montair LC',         'Montelukast + Levocetirizine',            NULL, '10mg+5mg', 'Tablet',    'allopathy'),
('Allegra',            'Fexofenadine',                            NULL, '120mg',    'Tablet',    'allopathy'),
('Atarax',             'Hydroxyzine',                             NULL, '25mg',     'Tablet',    'allopathy'),
('Deriphyllin',        'Etofylline + Theophylline',               NULL, NULL,       'Tablet',    'allopathy'),
('Asthalin',           'Salbutamol',                              NULL, '100mcg',   'Inhaler',   'allopathy'),
('Ventolin',           'Salbutamol',                              NULL, '100mcg',   'Inhaler',   'allopathy'),
('Budecort',           'Budesonide',                              NULL, '200mcg',   'Inhaler',   'allopathy'),
('Seroflo',            'Fluticasone + Salmeterol',                NULL, '250/25mcg','Inhaler',   'allopathy'),
('Foracort',           'Budesonide + Formoterol',                 NULL, '200/6mcg', 'Inhaler',   'allopathy'),
('Voveran',            'Diclofenac',                              NULL, '50mg',     'Tablet',    'allopathy'),
('Brufen',             'Ibuprofen',                               NULL, '400mg',    'Tablet',    'allopathy'),
('Combiflam',          'Ibuprofen + Paracetamol',                 NULL, '400/325mg','Tablet',    'allopathy'),
('Zerodol',            'Aceclofenac',                             NULL, '100mg',    'Tablet',    'allopathy'),
('Hifenac',            'Aceclofenac',                             NULL, '100mg',    'Tablet',    'allopathy'),
('Etoshine',           'Etoricoxib',                              NULL, '90mg',     'Tablet',    'allopathy'),
('Arcoxia',            'Etoricoxib',                              NULL, '90mg',     'Tablet',    'allopathy'),
('Ultracet',           'Tramadol + Paracetamol',                  NULL, '37.5/325mg','Tablet',   'allopathy'),
('Tramazac',           'Tramadol',                                NULL, '50mg',     'Capsule',   'allopathy'),
('Pregaba',            'Pregabalin',                              NULL, '75mg',     'Capsule',   'allopathy'),
('Lyrica',             'Pregabalin',                              NULL, '75mg',     'Capsule',   'allopathy'),
('Gabapin',            'Gabapentin',                              NULL, '300mg',    'Capsule',   'allopathy'),
('Rejoint',            'Diacerhein + Glucosamine',                NULL, NULL,       'Capsule',   'allopathy'),
('Phexin',             'Cephalexin',                              NULL, '500mg',    'Capsule',   'allopathy'),
('Sporidex',           'Cephalexin',                              NULL, '500mg',    'Capsule',   'allopathy'),
('Doxycycline',        'Doxycycline',                             NULL, '100mg',    'Capsule',   'allopathy'),
('Doxt-SL',            'Doxycycline',                             NULL, '100mg',    'Capsule',   'allopathy'),
('Nexpro',             'Esomeprazole',                            NULL, '40mg',     'Tablet',    'allopathy'),
('Nexium',             'Esomeprazole',                            NULL, '40mg',     'Tablet',    'allopathy'),
('Rablet',             'Rabeprazole',                             NULL, '20mg',     'Tablet',    'allopathy'),
('Razo',               'Rabeprazole',                             NULL, '20mg',     'Tablet',    'allopathy'),
('Domperidone',        'Domperidone',                             NULL, '10mg',     'Tablet',    'allopathy'),
('Domstal',            'Domperidone',                             NULL, '10mg',     'Tablet',    'allopathy'),
('Perinorm',           'Metoclopramide',                          NULL, '10mg',     'Tablet',    'allopathy'),
('Ondansetron',        'Ondansetron',                             NULL, '4mg',      'Tablet',    'allopathy'),
('Emeset',             'Ondansetron',                             NULL, '4mg',      'Tablet',    'allopathy'),
('ORS',                'Oral Rehydration Salts',                  NULL, NULL,       'Sachet',    'allopathy'),
('Electral',           'Oral Rehydration Salts',                  NULL, NULL,       'Powder',    'allopathy'),
('Normet',             'Metronidazole + Norfloxacin',             NULL, '400/400mg','Tablet',    'allopathy'),
('Econorm',            'Saccharomyces boulardii',                 NULL, '250mg',    'Capsule',   'allopathy'),
('Vizylac',            'Lactobacillus',                           NULL, NULL,       'Capsule',   'allopathy'),
('Sporlac',            'Lactobacillus',                           NULL, NULL,       'Tablet',    'allopathy'),
('Folvite',            'Folic Acid',                              NULL, '5mg',      'Tablet',    'allopathy'),
('Hb Tone',            'Iron + Folic Acid',                       NULL, NULL,       'Syrup',     'allopathy'),
('Dexorange',          'Iron + Folic Acid + Vitamin B12',         NULL, NULL,       'Syrup',     'allopathy'),
('Ferium XT',          'Ferrous Ascorbate + Folic Acid',          NULL, NULL,       'Tablet',    'allopathy'),
('Thyronorm',          'Levothyroxine',                           NULL, '50mcg',    'Tablet',    'allopathy'),
('Eltroxin',           'Levothyroxine',                           NULL, '50mcg',    'Tablet',    'allopathy'),
('Furosemide',         'Furosemide',                              NULL, '40mg',     'Tablet',    'allopathy'),
('Lasix',              'Furosemide',                              NULL, '40mg',     'Tablet',    'allopathy'),
('Dytor',              'Torasemide',                              NULL, '10mg',     'Tablet',    'allopathy'),
('Aldactone',          'Spironolactone',                          NULL, '25mg',     'Tablet',    'allopathy'),
('Clopilet',           'Clopidogrel',                             NULL, '75mg',     'Tablet',    'allopathy'),
('Plavix',             'Clopidogrel',                             NULL, '75mg',     'Tablet',    'allopathy'),
('Concor',             'Bisoprolol',                              NULL, '5mg',      'Tablet',    'allopathy'),
('Bisoprolol',         'Bisoprolol',                              NULL, '5mg',      'Tablet',    'allopathy'),
('Digoxin',            'Digoxin',                                 NULL, '0.25mg',   'Tablet',    'allopathy'),
('Lanoxin',            'Digoxin',                                 NULL, '0.25mg',   'Tablet',    'allopathy'),
('Amiodarone',         'Amiodarone',                              NULL, '200mg',    'Tablet',    'allopathy'),
('Cordarone',          'Amiodarone',                              NULL, '200mg',    'Tablet',    'allopathy'),
('Erythromycin',       'Erythromycin',                            NULL, '250mg',    'Tablet',    'allopathy'),
('Althrocin',          'Erythromycin',                            NULL, '250mg',    'Tablet',    'allopathy'),
('Zovirax',            'Acyclovir',                               NULL, '400mg',    'Tablet',    'allopathy'),
('Acivir',             'Acyclovir',                               NULL, '400mg',    'Tablet',    'allopathy'),
('Valtrex',            'Valacyclovir',                            NULL, '500mg',    'Tablet',    'allopathy'),
('Fluconazole',        'Fluconazole',                             NULL, '150mg',    'Tablet',    'allopathy'),
('Flucos',             'Fluconazole',                             NULL, '150mg',    'Tablet',    'allopathy'),
('Itraconazole',       'Itraconazole',                            NULL, '100mg',    'Capsule',   'allopathy'),
('Canditral',          'Itraconazole',                            NULL, '100mg',    'Capsule',   'allopathy'),
('Terbinafine',        'Terbinafine',                             NULL, '250mg',    'Tablet',    'allopathy'),
('Terbicip',           'Terbinafine',                             NULL, '250mg',    'Tablet',    'allopathy'),
('Mintop',             'Minoxidil',                               NULL, '5%',       'Solution',  'allopathy'),
('Finast',             'Finasteride',                             NULL, '1mg',      'Tablet',    'allopathy'),
('Clotrimazole',       'Clotrimazole',                            NULL, '1%',       'Cream',     'allopathy'),
('Candid',             'Clotrimazole',                            NULL, '1%',       'Cream',     'allopathy'),
('HCQS',               'Hydroxychloroquine',                      NULL, '200mg',    'Tablet',    'allopathy'),
('Plaquenil',          'Hydroxychloroquine',                      NULL, '200mg',    'Tablet',    'allopathy'),
('Saaz',               'Sulfasalazine',                           NULL, '500mg',    'Tablet',    'allopathy'),
('Folitrax',           'Methotrexate',                            NULL, '7.5mg',    'Tablet',    'allopathy'),
('Ivecop',             'Ivermectin',                              NULL, '12mg',     'Tablet',    'allopathy'),
('Zentel',             'Albendazole',                             NULL, '400mg',    'Tablet',    'allopathy'),
('Bandy',              'Albendazole',                             NULL, '400mg',    'Tablet',    'allopathy'),
('Rivotril',           'Clonazepam',                              NULL, '0.5mg',    'Tablet',    'allopathy'),
('Alprax',             'Alprazolam',                              NULL, '0.25mg',   'Tablet',    'allopathy'),
('Calmpose',           'Diazepam',                                NULL, '5mg',      'Tablet',    'allopathy'),
('Nexito',             'Escitalopram',                            NULL, '10mg',     'Tablet',    'allopathy'),
('Sertima',            'Sertraline',                              NULL, '50mg',     'Tablet',    'allopathy'),
('Paxidep',            'Paroxetine',                              NULL, '20mg',     'Tablet',    'allopathy'),
('Mirtaz',             'Mirtazapine',                             NULL, '15mg',     'Tablet',    'allopathy'),
('Oleanz',             'Olanzapine',                              NULL, '5mg',      'Tablet',    'allopathy'),
('Qutipin',            'Quetiapine',                              NULL, '25mg',     'Tablet',    'allopathy'),
('Sizodon',            'Risperidone',                             NULL, '2mg',      'Tablet',    'allopathy'),
('Eptoin',             'Phenytoin',                               NULL, '100mg',    'Tablet',    'allopathy'),
('Valparin',           'Sodium Valproate',                        NULL, '200mg',    'Tablet',    'allopathy'),
('Oxetol',             'Oxcarbazepine',                           NULL, '300mg',    'Tablet',    'allopathy'),
('Levroxa',            'Levetiracetam',                           NULL, '500mg',    'Tablet',    'allopathy'),
('Nootropil',          'Piracetam',                               NULL, '800mg',    'Tablet',    'allopathy'),
('Aricept',            'Donepezil',                               NULL, '10mg',     'Tablet',    'allopathy'),
('Manforce',           'Sildenafil',                              NULL, '100mg',    'Tablet',    'allopathy'),
('Urimax',             'Tamsulosin',                              NULL, '0.4mg',    'Capsule',   'allopathy'),
('Dutas',              'Dutasteride',                             NULL, '0.5mg',    'Capsule',   'allopathy'),
('Unwanted 72',        'Levonorgestrel',                          NULL, '1.5mg',    'Tablet',    'allopathy'),
('i-Pill',             'Levonorgestrel',                          NULL, '1.5mg',    'Tablet',    'allopathy'),
('Mifepristone',       'Mifepristone',                            NULL, '200mg',    'Tablet',    'allopathy'),
('Misoprostol',        'Misoprostol',                             NULL, '200mcg',   'Tablet',    'allopathy'),
('Susten',             'Progesterone',                            NULL, '200mg',    'Capsule',   'allopathy'),
('Duphaston',          'Dydrogesterone',                          NULL, '10mg',     'Tablet',    'allopathy'),
('Primolut',           'Norethisterone',                          NULL, '5mg',      'Tablet',    'allopathy'),
('Siphene',            'Clomiphene',                              NULL, '50mg',     'Tablet',    'allopathy'),
('Drotin',             'Drotaverine',                             NULL, '40mg',     'Tablet',    'allopathy'),
('Depin',              'Nifedipine',                              NULL, '10mg',     'Tablet',    'allopathy'),
('Methergin',          'Methylergometrine',                       NULL, '0.2mg',    'Tablet',    'allopathy'),
('Betnesol',           'Betamethasone',                           NULL, '0.5mg',    'Tablet',    'allopathy'),
('Macrobid',           'Nitrofurantoin',                          NULL, '100mg',    'Capsule',   'allopathy'),
('Amikin',             'Amikacin',                                NULL, '500mg',    'Injection', 'allopathy'),
('Meronem',            'Meropenem',                               NULL, '1g',       'Injection', 'allopathy'),
('Tazact',             'Piperacillin + Tazobactam',               NULL, '4.5g',     'Injection', 'allopathy'),
('Lizolid',            'Linezolid',                               NULL, '600mg',    'Tablet',    'allopathy'),
('Nitrocontin',        'Isosorbide Mononitrate',                  NULL, '20mg',     'Tablet',    'allopathy'),
('Olmesar',            'Olmesartan',                              NULL, '20mg',     'Tablet',    'allopathy'),
('Acitrom',            'Acenocoumarol',                           NULL, '1mg',      'Tablet',    'allopathy'),
-- Common Ayurvedic
('Ashwagandha',        'Withania somnifera',                      NULL, '500mg',    'Capsule',   'ayurvedic'),
('Triphala',           'Amalaki + Haritaki + Vibhitaki',          NULL, NULL,       'Tablet',    'ayurvedic'),
('Chyawanprash',       'Polyherbal',                              NULL, NULL,       'Paste',     'ayurvedic'),
('Brahmi',             'Bacopa monnieri',                         NULL, '300mg',    'Tablet',    'ayurvedic'),
('Shilajit',           'Purified Shilajit',                       NULL, '250mg',    'Capsule',   'ayurvedic'),
('Tulsi',              'Ocimum sanctum',                          NULL, '500mg',    'Tablet',    'ayurvedic'),
('Neem',               'Azadirachta indica',                      NULL, '500mg',    'Capsule',   'ayurvedic'),
('Haridra',            'Curcuma longa (Turmeric)',                 NULL, '500mg',    'Capsule',   'ayurvedic'),
('Guduchi',            'Tinospora cordifolia',                    NULL, '500mg',    'Tablet',    'ayurvedic'),
('Karela',             'Momordica charantia',                     NULL, '500mg',    'Capsule',   'ayurvedic'),
('Liv 52',             'Polyherbal liver tonic',                  'Himalaya', NULL, 'Tablet',    'ayurvedic'),
('Cystone',            'Polyherbal urinary support',              'Himalaya', NULL, 'Tablet',    'ayurvedic'),
('Confido',            'Polyherbal male tonic',                   'Himalaya', NULL, 'Tablet',    'ayurvedic'),
('Septilin',           'Polyherbal immune support',               'Himalaya', NULL, 'Tablet',    'ayurvedic'),
('Tentex Forte',       'Polyherbal',                              'Himalaya', NULL, 'Tablet',    'ayurvedic'),
('Rumalaya',           'Polyherbal joint support',                'Himalaya', NULL, 'Tablet',    'ayurvedic'),
('Diabecon',           'Polyherbal diabetic support',             'Himalaya', NULL, 'Tablet',    'ayurvedic'),
('Bonnisan',           'Polyherbal digestive for infants',        'Himalaya', NULL, 'Syrup',     'ayurvedic'),
('Pudinhara',          'Peppermint oil',                          'Dabur',    NULL, 'Capsule',   'ayurvedic'),
('Hajmola',            'Digestive herbal',                        'Dabur',    NULL, 'Tablet',    'ayurvedic'),
('Shankha Bhasma',     'Conch shell calx',                        NULL,       NULL, 'Powder',    'ayurvedic'),
('Swarna Bhasma',      'Gold calx',                               NULL,       NULL, 'Powder',    'ayurvedic'),
('Arogyavardhini Vati','Polyherbal',                              NULL,       NULL, 'Tablet',    'ayurvedic'),
('Chandraprabha Vati', 'Polyherbal urinary',                      NULL,       NULL, 'Tablet',    'ayurvedic'),
('Dashmoola',          'Ten roots decoction',                     NULL,       NULL, 'Tablet',    'ayurvedic'),
('Hingwashtak Churna', 'Carminative powder',                      NULL,       NULL, 'Powder',    'ayurvedic'),
('Trikatu',            'Ginger + Black pepper + Long pepper',     NULL,       NULL, 'Tablet',    'ayurvedic'),
('Mahasudarshan',      'Polyherbal antipyretic',                  NULL,       NULL, 'Tablet',    'ayurvedic'),
('Abana',              'Polyherbal cardiac',                      'Himalaya', NULL, 'Tablet',    'ayurvedic'),
('Gasex',              'Polyherbal antiflatulent',                'Himalaya', NULL, 'Tablet',    'ayurvedic'),
('Mentat',             'Polyherbal nootropic',                    'Himalaya', NULL, 'Tablet',    'ayurvedic'),
-- ── Homeopathy ────────────────────────────────────────────────────────────────
('Arnica Montana 30C', 'Arnica montana',             'SBL',          '30C',  'Globules',  'homeopathy'),
('Arnica Montana 200C','Arnica montana',             'SBL',          '200C', 'Globules',  'homeopathy'),
('Arnica Hair Oil',    'Arnica montana',             'SBL',          'Q',    'Oil',       'homeopathy'),
('Belladonna 30C',     'Belladonna',                 'Boiron',       '30C',  'Globules',  'homeopathy'),
('Belladonna 200C',    'Belladonna',                 'Boiron',       '200C', 'Globules',  'homeopathy'),
('Bryonia 30C',        'Bryonia alba',               'SBL',          '30C',  'Globules',  'homeopathy'),
('Bryonia 200C',       'Bryonia alba',               'SBL',          '200C', 'Globules',  'homeopathy'),
('Nux Vomica 30C',     'Nux vomica',                 'SBL',          '30C',  'Globules',  'homeopathy'),
('Nux Vomica 200C',    'Nux vomica',                 'SBL',          '200C', 'Globules',  'homeopathy'),
('Rhus Tox 30C',       'Rhus toxicodendron',         'SBL',          '30C',  'Globules',  'homeopathy'),
('Rhus Tox 200C',      'Rhus toxicodendron',         'SBL',          '200C', 'Globules',  'homeopathy'),
('Pulsatilla 30C',     'Pulsatilla nigricans',       'SBL',          '30C',  'Globules',  'homeopathy'),
('Lycopodium 30C',     'Lycopodium',                 'SBL',          '30C',  'Globules',  'homeopathy'),
('Lycopodium 200C',    'Lycopodium',                 'SBL',          '200C', 'Globules',  'homeopathy'),
('Sulphur 30C',        'Sulphur',                    'SBL',          '30C',  'Globules',  'homeopathy'),
('Sulphur 200C',       'Sulphur',                    'SBL',          '200C', 'Globules',  'homeopathy'),
('Calcarea Carb 30C',  'Calcarea carbonica',         'SBL',          '30C',  'Globules',  'homeopathy'),
('Calcarea Carb 200C', 'Calcarea carbonica',         'SBL',          '200C', 'Globules',  'homeopathy'),
('Phosphorus 30C',     'Phosphorus',                 'SBL',          '30C',  'Globules',  'homeopathy'),
('Phosphorus 200C',    'Phosphorus',                 'SBL',          '200C', 'Globules',  'homeopathy'),
('Sepia 30C',          'Sepia officinalis',          'SBL',          '30C',  'Globules',  'homeopathy'),
('Natrum Mur 30C',     'Natrum muriaticum',          'SBL',          '30C',  'Globules',  'homeopathy'),
('Natrum Mur 6X',      'Natrum muriaticum',          'SBL',          '6X',   'Biochemic', 'homeopathy'),
('Apis Mel 30C',       'Apis mellifica',             'SBL',          '30C',  'Globules',  'homeopathy'),
('Gelsemium 30C',      'Gelsemium sempervirens',     'SBL',          '30C',  'Globules',  'homeopathy'),
('Ignatia Amara 30C',  'Ignatia amara',              'SBL',          '30C',  'Globules',  'homeopathy'),
('Aconite Napellus 30C','Aconitum napellus',         'SBL',          '30C',  'Globules',  'homeopathy'),
('Hepar Sulph 30C',    'Hepar sulphuris calcareum',  'SBL',          '30C',  'Globules',  'homeopathy'),
('Silicea 6X',         'Silicea',                    'SBL',          '6X',   'Biochemic', 'homeopathy'),
('Silicea 30C',        'Silicea',                    'SBL',          '30C',  'Globules',  'homeopathy'),
('Kali Bichromicum 30C','Kalium bichromicum',        'SBL',          '30C',  'Globules',  'homeopathy'),
('Drosera 30C',        'Drosera rotundifolia',       'SBL',          '30C',  'Globules',  'homeopathy'),
('Cantharis 30C',      'Cantharis',                  'SBL',          '30C',  'Globules',  'homeopathy'),
('Merc Sol 30C',       'Mercurius solubilis',        'SBL',          '30C',  'Globules',  'homeopathy'),
('Thuja 30C',          'Thuja occidentalis',         'SBL',          '30C',  'Globules',  'homeopathy'),
('Thuja 200C',         'Thuja occidentalis',         'SBL',          '200C', 'Globules',  'homeopathy'),
('Staphysagria 30C',   'Staphysagria',               'SBL',          '30C',  'Globules',  'homeopathy'),
('Cocculus Indicus 30C','Cocculus indicus',          'SBL',          '30C',  'Globules',  'homeopathy'),
('Carbo Veg 30C',      'Carbo vegetabilis',          'SBL',          '30C',  'Globules',  'homeopathy'),
('Lachesis 30C',       'Lachesis mutus',             'SBL',          '30C',  'Globules',  'homeopathy'),
('Lachesis 200C',      'Lachesis mutus',             'SBL',          '200C', 'Globules',  'homeopathy'),
('Hamamelis 30C',      'Hamamelis virginiana',       'SBL',          '30C',  'Globules',  'homeopathy'),
('Ferrum Phos 6X',     'Ferrum phosphoricum',        'SBL',          '6X',   'Biochemic', 'homeopathy'),
('Kali Phos 6X',       'Kalium phosphoricum',        'SBL',          '6X',   'Biochemic', 'homeopathy'),
('Mag Phos 6X',        'Magnesium phosphoricum',     'SBL',          '6X',   'Biochemic', 'homeopathy'),
('Calc Fluor 6X',      'Calcarea fluorica',          'SBL',          '6X',   'Biochemic', 'homeopathy'),
('Biocombination BC1', 'Anaemia biochemic combination','SBL',        NULL,   'Tablet',    'homeopathy'),
('Biocombination BC7', 'Cough biochemic combination','SBL',          NULL,   'Tablet',    'homeopathy'),
('Biocombination BC11','Fever biochemic combination','SBL',          NULL,   'Tablet',    'homeopathy'),
('Biocombination BC17','Worms biochemic combination','SBL',          NULL,   'Tablet',    'homeopathy'),
('Biocombination BC20','Skin biochemic combination', 'SBL',          NULL,   'Tablet',    'homeopathy'),
('Biocombination BC25','Acidity biochemic combination','SBL',        NULL,   'Tablet',    'homeopathy'),
('Five Phos Biochemic','Five phosphates combination','SBL',          NULL,   'Tablet',    'homeopathy'),
('Dr. Reckeweg R1',    'Inflammation drops',         'Dr. Reckeweg', NULL,   'Drops',     'homeopathy'),
('Dr. Reckeweg R2',    'Heart drops',                'Dr. Reckeweg', NULL,   'Drops',     'homeopathy'),
('Dr. Reckeweg R3',    'Heart efficiency drops',     'Dr. Reckeweg', NULL,   'Drops',     'homeopathy'),
('Dr. Reckeweg R4',    'Diarrhoea drops',            'Dr. Reckeweg', NULL,   'Drops',     'homeopathy'),
('Dr. Reckeweg R6',    'Fever drops',                'Dr. Reckeweg', NULL,   'Drops',     'homeopathy'),
('Dr. Reckeweg R11',   'Rheumatism drops',           'Dr. Reckeweg', NULL,   'Drops',     'homeopathy'),
('Dr. Reckeweg R17',   'Tumour drops',               'Dr. Reckeweg', NULL,   'Drops',     'homeopathy'),
('Dr. Reckeweg R41',   'Sexual neurasthenia drops',  'Dr. Reckeweg', NULL,   'Drops',     'homeopathy'),
('Dr. Reckeweg R89',   'Hair care drops',            'Dr. Reckeweg', NULL,   'Drops',     'homeopathy'),
('Bakson B1',          'Tonsil drops',               'Bakson',       NULL,   'Drops',     'homeopathy'),
('Bakson B9',          'Kidney drops',               'Bakson',       NULL,   'Drops',     'homeopathy'),
('Bakson B15',         'Skin drops',                 'Bakson',       NULL,   'Drops',     'homeopathy'),
('Allen A1',           'Acne drops',                 'Allen',        NULL,   'Drops',     'homeopathy'),
('Allen A11',          'Hairfall drops',             'Allen',        NULL,   'Drops',     'homeopathy'),
('Allen A30',          'Asthma drops',               'Allen',        NULL,   'Drops',     'homeopathy'),
('Allen A55',          'Thyroid drops',              'Allen',        NULL,   'Drops',     'homeopathy'),
('Lords L72',          'Anxiety drops',              'Lords',        NULL,   'Drops',     'homeopathy'),
('Lords L74',          'Memory drops',               'Lords',        NULL,   'Drops',     'homeopathy'),
('Adel 1 Apo-Dolor',   'Pain drops',                 'Adel',         NULL,   'Drops',     'homeopathy'),
('Wheezal WL-10',      'Cough & bronchitis drops',   'Wheezal',      NULL,   'Drops',     'homeopathy'),
('Blooume 7 Sinusan',  'Sinus drops',                'Blooume',      NULL,   'Drops',     'homeopathy'),
('Schwabe Topi Amica', 'Arnica montana topical',     'Schwabe',      NULL,   'Cream',     'homeopathy')

ON CONFLICT DO NOTHING;

-- ── COPY from CSV (uncomment and set path when you have the CDSCO/Kaggle CSV) ─
-- Run this block manually via psql after downloading the CSV:
--
-- \COPY drug_catalog (brand_name, generic_name, manufacturer, strength, dosage_form, category, schedule)
-- FROM '/path/to/indian_drugs.csv'
-- WITH (FORMAT CSV, HEADER TRUE, NULL '');
--
-- Or use the helper script which handles any CSV column order:
--   bash /opt/infer/backend/scripts/seed_drugs.sh /path/to/indian_drugs.csv
