const router = require('express').Router();
const { register, login, refresh, logout, getMe, updateProfile, forgotPassword } = require('../controllers/auth.controller');
const { loginStaff } = require('../emr/emr.labstaff.controller');
const auth = require('../middleware/auth');
router.post('/register', register);
router.post('/login', login);
router.post('/refresh', refresh);
router.post('/logout', auth, logout);
router.get('/me', auth, getMe);
router.put('/profile', auth, updateProfile);
router.post('/forgot-password', forgotPassword);
router.post('/lab/login', loginStaff);
module.exports = router;
